### ISSUE TITLE
bug:生成的文件格式有问题

### ISSUE THREAD

**Issue by WuDiTangYuan** [HuolalaTech/hll-wp-guldan-ios#1]
+ 使用下面的样例代码，只监控一个方法的耗时，最后的生成的文件有问题
```
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [GDNOCMethodTimeProfiler start];
    [self testFuncA];
    [GDNOCMethodTimeProfiler stop];
    
    [GDNOCMethodTimeProfiler handleRecordsWithComplete:^(NSArray<NSString *> * _Nonnull filePaths) {
        // file path
    }];
}

- (void)testFuncA {
    int a = 0;
    for (int i = 0; i <= 1000; i++) {
        a = a + i;
    }
    NSLog(@"%d",a);
}
```
+ 经过检查发现是因为生成文件的方法存在问题，建议完善文件生成逻辑，只监控一个方法时 recordsCount 为1，会生成一个只包含 [ 的文件。
```
for (unsigned int i = 0; i < recordsCount; i++) {
            @autoreleasepool {
                gdn_stack_entry_t stackEntry = threadInfo->stackEntries[i];
                Class cls = (__bridge Class _Nullable)(stackEntry.cls);
                BOOL isClassMethod = class_isMetaClass(cls);
                const char *className = class_getName(cls);
                char *selName = stackEntry.cmd;
                
                if (cls && strlen(className) > 0 && strlen(selName) > 0) {
                    NSDictionary *pieceDic = @{
                        @"name": [NSString stringWithFormat:@"%@[%s %s]",(isClassMethod ? @"+" : @"-"), className, selName],
                        @"tname": threadName,
                        @"st": @(stackEntry.start_time * 1e6),
                        @"consume": @(stackEntry.consume_time * 1e6),
                        @"args": @{
                            @"stack_depth": @(stackEntry.stack_depth),
                            @"shallow_consume": @(stackEntry.shallow_consume_time * 1e6),
                        }
                    };
                    NSData *pieceData = [NSJSONSerialization dataWithJSONObject:pieceDic
                                                                    options:NSJSONWritingPrettyPrinted
                                                                      error:nil];
                    if (i == 0) {
                        [dataM appendData:[@"[" dataUsingEncoding:NSUTF8StringEncoding]];
                    } else if (i == recordsCount - 1) {
                        [dataM appendData:[@"]" dataUsingEncoding:NSUTF8StringEncoding]];
                    } else {
                        [dataM appendData:pieceData];
                        [dataM appendData:[@"," dataUsingEncoding:NSUTF8StringEncoding]];
                    }
                }
            }
        }
```

**Comment by wulongwang** [comment]
[ { "tname": "mainthread", "st": 2000761.833274737, "args": { "stack_depth": 0, "shallow_consume": 1000000 }, "name": "-[GDAppDelegate delegateM2]", "consume": 978377.91661731899 }, { "tname": "mainthread", "st": 0.083353370428085327, "args": { "stack_depth": 0, "shallow_consume": 0 }, "name": "-[GDAppDelegate testDelegate]", "consume": 2979191.7914990336 }, { "tname": "mainthread", "st": 4999519.7500102222, "args": { "stack_depth": 0, "shallow_consume": 4000000 }, "name": "-[OS_dispatch_mach_msg dealloc]", "consume": 123.5415693372488 }, { "tname": "mainthread", "st": 4999518.9583860338, "args": { "stack_depth": 0, "shallow_consume": 3000000 }, "name": "-[OS_xpc_serializer dealloc]", "consume": 127.4582464247942 }, { "tname": "mainthread", "st": 5579742.9583035409, "args": { "stack_depth": 0, "shallow_consume": 3000000 }, "name": "-[OS_xpc_dictionary dealloc]", "consume": 103.12488302588463 }, { "tname": "mainthread", "st": 4984907.0415366441, "args": { "stack_depth": 0, "shallow_consume": 2000000 }, "name": "-[GDViewController m3]", "consume": 656005.87497465312 }, { "tname": "mainthread", "st": 6156907.4583239853, "args": { "stack_depth": 0, "shallow_consume": 4000000 }, "name": "-[OS_xpc_string dealloc]", "consume": 131.16654008626938 }, { "tname": "mainthread", "st": 6156904.0832109749, "args": { "stack_depth": 0, "shallow_consume": 3000000 }, "name": "-[OS_xpc_dictionary dealloc]", "consume": 135.54166071116924 }, { "tname": "mainthread", "st": 5640913.9581955969, "args": { "stack_depth": 0, "shallow_consume": 2000000 }, "name": "-[GDViewController m3]", "consume": 575004.54178079963 }, { "tname": "mainthread", "st": 2983831.7916728556, "args": { "stack_depth": 2, "shallow_consume": 1000000 }, "name": "-[GDViewController m1]", "consume": 3232087.0831608772 } ]

这个json文件，拖到 chrome://tracing/ 显示不了？

**Comment by wulongwang** [comment]
> * 使用下面的样例代码，只监控一个方法的耗时，最后的生成的文件有问题
> 
> ```
> - (void)viewDidLoad {
>     [super viewDidLoad];
>     // Do any additional setup after loading the view.
>     [GDNOCMethodTimeProfiler start];
>     [self testFuncA];
>     [GDNOCMethodTimeProfiler stop];
>     
>     [GDNOCMethodTimeProfiler handleRecordsWithComplete:^(NSArray<NSString *> * _Nonnull filePaths) {
>         // file path
>     }];
> }
> 
> - (void)testFuncA {
>     int a = 0;
>     for (int i = 0; i <= 1000; i++) {
>         a = a + i;
>     }
>     NSLog(@"%d",a);
> }
> ```
> 
> * 经过检查发现是因为生成文件的方法存在问题，建议完善文件生成逻辑，只监控一个方法时 recordsCount 为1，会生成一个只包含 [ 的文件。
> 
> ```
> for (unsigned int i = 0; i < recordsCount; i++) {
>             @autoreleasepool {
>                 gdn_stack_entry_t stackEntry = threadInfo->stackEntries[i];
>                 Class cls = (__bridge Class _Nullable)(stackEntry.cls);
>                 BOOL isClassMethod = class_isMetaClass(cls);
>                 const char *className = class_getName(cls);
>                 char *selName = stackEntry.cmd;
>                 
>                 if (cls && strlen(className) > 0 && strlen(selName) > 0) {
>                     NSDictionary *pieceDic = @{
>                         @"name": [NSString stringWithFormat:@"%@[%s %s]",(isClassMethod ? @"+" : @"-"), className, selName],
>                         @"tname": threadName,
>                         @"st": @(stackEntry.start_time * 1e6),
>                         @"consume": @(stackEntry.consume_time * 1e6),
>                         @"args": @{
>                             @"stack_depth": @(stackEntry.stack_depth),
>                             @"shallow_consume": @(stackEntry.shallow_consume_time * 1e6),
>                         }
>                     };
>                     NSData *pieceData = [NSJSONSerialization dataWithJSONObject:pieceDic
>                                                                     options:NSJSONWritingPrettyPrinted
>                                                                       error:nil];
>                     if (i == 0) {
>                         [dataM appendData:[@"[" dataUsingEncoding:NSUTF8StringEncoding]];
>                     } else if (i == recordsCount - 1) {
>                         [dataM appendData:[@"]" dataUsingEncoding:NSUTF8StringEncoding]];
>                     } else {
>                         [dataM appendData:pieceData];
>                         [dataM appendData:[@"," dataUsingEncoding:NSUTF8StringEncoding]];
>                     }
>                 }
>             }
>         }
> ```

生成的json 文件 拖到 chrome://tracing/  能展示吗

**Comment by GFGWin** [comment]
确实是，这边demo跑出来的文件在chrome中不能展示，另外在我真实项目中会在加载汇编指令 blr x9 的时候崩溃。。。

**Comment by fantexi023** [comment]
近期会更新代码

**Comment by fantexi023** [comment]
> * 使用下面的样例代码，只监控一个方法的耗时，最后的生成的文件有问题
> 
> ```
> - (void)viewDidLoad {
>     [super viewDidLoad];
>     // Do any additional setup after loading the view.
>     [GDNOCMethodTimeProfiler start];
>     [self testFuncA];
>     [GDNOCMethodTimeProfiler stop];
>     
>     [GDNOCMethodTimeProfiler handleRecordsWithComplete:^(NSArray<NSString *> * _Nonnull filePaths) {
>         // file path
>     }];
> }
> 
> - (void)testFuncA {
>     int a = 0;
>     for (int i = 0; i <= 1000; i++) {
>         a = a + i;
>     }
>     NSLog(@"%d",a);
> }
> ```
> 
> * 经过检查发现是因为生成文件的方法存在问题，建议完善文件生成逻辑，只监控一个方法时 recordsCount 为1，会生成一个只包含 [ 的文件。
> 
> ```
> for (unsigned int i = 0; i < recordsCount; i++) {
>             @autoreleasepool {
>                 gdn_stack_entry_t stackEntry = threadInfo->stackEntries[i];
>                 Class cls = (__bridge Class _Nullable)(stackEntry.cls);
>                 BOOL isClassMethod = class_isMetaClass(cls);
>                 const char *className = class_getName(cls);
>                 char *selName = stackEntry.cmd;
>                 
>                 if (cls && strlen(className) > 0 && strlen(selName) > 0) {
>                     NSDictionary *pieceDic = @{
>                         @"name": [NSString stringWithFormat:@"%@[%s %s]",(isClassMethod ? @"+" : @"-"), className, selName],
>                         @"tname": threadName,
>                         @"st": @(stackEntry.start_time * 1e6),
>                         @"consume": @(stackEntry.consume_time * 1e6),
>                         @"args": @{
>                             @"stack_depth": @(stackEntry.stack_depth),
>                             @"shallow_consume": @(stackEntry.shallow_consume_time * 1e6),
>                         }
>                     };
>                     NSData *pieceData = [NSJSONSerialization dataWithJSONObject:pieceDic
>                                                                     options:NSJSONWritingPrettyPrinted
>                                                                       error:nil];
>                     if (i == 0) {
>                         [dataM appendData:[@"[" dataUsingEncoding:NSUTF8StringEncoding]];
>                     } else if (i == recordsCount - 1) {
>                         [dataM appendData:[@"]" dataUsingEncoding:NSUTF8StringEncoding]];
>                     } else {
>                         [dataM appendData:pieceData];
>                         [dataM appendData:[@"," dataUsingEncoding:NSUTF8StringEncoding]];
>                     }
>                 }
>             }
>         }
> ```

已修复，请参阅新代码

**Comment by fantexi023** [comment]
> 确实是，这边demo跑出来的文件在chrome中不能展示，另外在我真实项目中会在加载汇编指令 blr x9 的时候崩溃。。。

已修复，请参阅新代码
