### ISSUE TITLE
crash when hook objc_message_send

### ISSUE THREAD

**Issue by NickNameWolf** [HuolalaTech/hll-wp-guldan-ios#3]
Xocde Version 14.3.1 (14E300c)
iPhone14Pro 
iOS 16.3.1

i catch a Assert when  start hook in didFinishLaunchingWithOptions

*** Assertion failure in _UIBoundingPathBitmapDataNode _UIBoundingPathBitmapDataNodeMake(BOOL, size_t)(), _UIBoundingPathBitmapData.h:100

exception description : columns value is too large to be stored in available space

**Comment by fantexi023** [comment]
请提供下didFinishLaunchingWithOptions中的使用代码和完整的堆栈
